#database configuration
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentcar?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      name:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL5Dialect
